@startuml
'https://plantuml.com/class-diagram
title Dinosaurio

abstract class Dinosaurio{
    -gestorCV: GestorCV
    -especie: string
    -edad: int
    -peso: int
    -hp_base: int
    -altura: int
    -Sexo sexo
    -tuvoHijos: boolean
    +Dinosaurio(especie: string, edad: int, peso: int, altura: int, sexo: Sexo, tuvoHijos: boolean)
    +getEspecie(): string
    +getEdad(): int
    +getPeso(): int
    +getAltura(): int
    +getSexo(): Sexo
    +getTuvoHijos(): boolean
}
enum Sexo{
    -MACHO
    -HEMBRA
}
class DinosaurioController{
    +mostrarDinosaurio(String especie): void
}
class DinosaurioDataStore{
    +cargarDatosCSV(String rutaCSV): void
    +dinosaurioDataStore(): void
    +getDinosaurio(String especie): Dinosaurio
}
class DinosaurioView{
    +mostrarDinosaurio(Dinosaurio): void
}

class DinosaurioBuilder{
    +caracteristicaRara(): void
    +build(): Dinosaurio
}

abstract class DinosauroFactory{
    +crearDinosaurio(tipo: String): Dinosaurio
}

class CarnivoroFactory extends DinosauroFactory{}
class HerbivoroFactory extends DinosauroFactory{}
class OmnivoroFactory extends DinosauroFactory{}

abstract class FactoriaInstalaciones{
    +crearInstalacion(): Instalacion
}

class Instalacion{
    -nombre: string
    -capacidad: int
    -temperatura: int
    -tipo: string
    -terreno: int
    +Instalacion(terreno: int, nombre: string, capacidad: int, temperatura: int, tipo: string)
    +getNombre(): string
    +getCapacidad(): int
    +getTemperatura(): int
    +getTipo(): string
    +getTerrereno(): int
}

class Criadero extends Instalacion{}
class Laboratorio extends Instalacion{}
class Muelle extends Instalacion{}
class Puesto extends Instalacion{}

interface CiclodeVida{
    +nacer(): void
    +crecer(): void
    +adulto(): void
    +reproducir(): void
    +morir(): void
}

class GestorCV{
    +obtenerFase(Dinosaurio): void
    +iniciarCiclo(Dinosaurio): void
    +AvanzarFase(Dinosaurio): void
    +VerificarReproduccion(Dinosaurio): void
    +FaseAdulto(Dinosaurio): void
    +TerminarCiclo(Dinosaurio): void
    +seReproducio(Dinosaurio): void
    +verificarMadre(Dinosaurio): void
    +obtenerTiempoDeEsperaPorFase(FaseCicloDeVida): void
    +acelerarFase(FaseCicloDeVida): void
}

enum FaseCicloVida{
    -HUEVO
    -NACIMIENTO
    -CRECIMIENTO
    -ADULTO
    -REPRODUCCION
    -MUERTE
}
Sexo --> Dinosaurio
GestorCV *--> Dinosaurio
Herbivoro --> Dinosaurio
Carnivoro --> Dinosaurio
Omnivoro --> Dinosaurio
GestorCV ..|> CiclodeVida
DinosauroFactory ..> Dinosaurio
DinosaurioBuilder -> HerbivoroFactory
DinosaurioBuilder -> CarnivoroFactory
DinosaurioBuilder -> OmnivoroFactory
FactoriaInstalaciones ..> Instalacion
Dinosaurio --> DinosaurioController
Dinosaurio --> DinosaurioView
FaseCicloVida --> GestorCV


@enduml