@startuml
actor Usuario
participant GestorCV
participant DinosaurioService
participant DinosaurioFactory
participant DinosaurioRepository

Usuario -> GestorCV : Iniciar Reproduccion entre dino1 y dino2
GestorCV --> DinosaurioService : crear nuevo dino
DinosaurioService --> DinosaurioFactory : crearDinosaurio()
DinosaurioFactory --> DinosaurioService : Dinosaurio creado
DinosaurioService --> DinosaurioRepository : añade
DinosaurioRepository --> GestorCV : Dinosaurio añadido
GestorCV -> Usuario : "Reproducción completada"
@enduml
